### ISSUE TITLE
AST values converted to strings

### ISSUE THREAD

**Issue by mfikes** [lincoln-b/rage#1]
Because of the use of `cjls->js` [here](https://github.com/lincoln-b/rage/blob/4cdf089226f0c308c619ec3ae50d50f10813e0b8/src/rage/utilities.cljs#L31), if you evaluate a form like `:foo`, the form part of the AST will be displayed as `foo`.

**Comment by lwb4** [comment]
Is there a way to preserve keywords while converting to JSON?

I didn't think about the use case of copy-pasting the AST into another script; I just wanted a collapsible tree-view and couldn't find a library for doing that with ClojureScript maps. Could that be done with EDN?

I'm planning on adding a drop down on the right hand side where you can switch between viewing JSON and viewing the pretty printed map.

**Comment by mfikes** [comment]
@lincoln-b I think converting to string-based values is OK, but you may need to write your own `clj->js` that handles keywords by calling `str` on them.

**Comment by lwb4** [comment]
Oops, forgot to leave a comment. I reimplemented clj->js with str instead of name on keywords, preserving the starting colon.
